# Generated by Django 4.2.18 on 2025-01-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_App', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
